### ISSUE TITLE
概要を登録する @tbpgr

### ISSUE THREAD

**Issue by ariakira** [engineers-lt/rooting-book-1#15]
執筆内容を検討し、概要を **12月28日まで** に投稿してください。
まずは章立てと簡単な説明文から始めましょう。
これは、本全体の品質を決める大事なステップです。

**Comment by tbpgr** [comment]
@ariakira  合同誌ですが特に応募してなかったと思います。
（転職活動もあるし、手をあげないでいました）

**Comment by ariakira** [comment]
@tbpgr ほんとごめん！この合同誌チームに入ってる全員を割り当ててました。無視してください。

**Comment by tbpgr** [comment]
@ariakira もんだいないでーす。おつかれさまです
